name: Win Win
favicon: null
layout_spectrum: 0.6582471
typography_spectrum: 0.2870599
title: Win Win
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#a1d1ff'
    - '#5794e5'
    - '#2a3b59'
    - '#f0f5f8'
  brandStrength: 0.375
  lightness: 0.6797325
  saturation: 0.5943138
  rhythmicContrast: 0.4898876
purpose: []
