name: Win Win
favicon: null
layout_spectrum: 0.6582471
typography_spectrum: 0.2870599
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3693459
  lightness: 0.6797325
  saturation: 0.5943138
  rhythmicContrast: 0.4898876
purpose: []
